const words = [
    'Mentions Palmer',
    'Mentions Locke',
    'Mentions Bismarck',
    'Mentions how WWI should have ended immediately',
    `"You cannot plan for a short war"`,
    `"I haven't graded it yet"`,
    `Yells at guys`,
    `Stands up and walks around for no reason`,
    `Complains about faculty meeting`,
    `Gets in an argument with Franco`,
    `Mentions Politelli`,
    `Complains about DBQ's`,
    `"Silver Chain"`,
    `"Mr. Perfect"`,
    `Randomly says something in German`,
    `Mentions buying more paper cups`,
    `Talks about modern day congressmen`,
    `Hamburger cars`,
    `Completely mispronounces a word`,
    `Someone asks a question and proceeds to talk about it for 10 minutes`,
    `Complains about the Promethean board`,
    `"Ms. Rauch you're going to be very upset"`,
    `Someone gets yelled at for using their phone`,
    `Extends a due date again`,
    `Zimmybub`,
    `Laughs uncontrolably at her own joke`,
    `Talks about her jewish background`,
    `"You can't 'what if?' history"`,
    `Uses the word arbitrary`,
    `Brings up Mr. Madoor`,
    `Calls Josh "gum wrapper"`,
    `Talks about current events completely unrelated to the subject`,
    `Complains about apple`,
    `Mentions the "big test"`,
    `Treaty of Versailles`,
    `Laughs at something dumb someone says unintentionally`,
    `Brings up art from the 1900's`,
    `"The failures of democracy"`,
    `Changes the due date of an assignment`
];